services:
  web:
    build:
      context: ./weather_app
    #command: mix phx.server
    #command: sh -c "mix phx.server"
    #command: sh -c "mix phx.server"
    #command: tail -f /dev/null
    volumes:
      - ./weather_app:/app
    #  - /app/des
    #  - /app/_build
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "ecto://weather-db:u_6QbMeb_crm9K4P@db:5432/weather-db"
    #restart: always
    networks:
      - weather_network

  db:
    image: postgres:16.2
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'weather-db'
      POSTGRES_PASSWORD: 'u_6QbMeb_crm9K4P'
      POSTGRES_DB: 'weather-db'
    volumes:
      - ./postgresql:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - weather_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - weather_network

networks:
  weather_network:
    driver: bridge