services:
  web:
    build:
      context: ./weather_app
    command: mix phx.server
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "ecto://weather-db:u_6QbMeb_crm9K4P@db:5432/weather-db"
  db:
    image: postgres:16.2
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'weather-db'
      POSTGRES_PASSWORD: 'u_6QbMeb_crm9K4P'
      POSTGRES_DB: 'weather-db'
    volumes:
      - ./postgresql:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    #networks:
    #  - miel_network
    #command: -p 5434
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    #networks:
    #  - miel_network